In [15]:
import pandas as pd

# Cargar archivo CSV
df = pd.read_csv(
    "C:/Users/Administrator/Desktop/Proyecto Personal_Estudio de la Procesionaria/dataset/DATASET_PROCESIONARIAS.csv", 
     on_bad_lines='skip',delimiter=';')

#on_bad_lines='skip'
# Vista previa de los datos
print(df.head())

       gbifID  accessRights  bibliographicCitation language    license  \
0  1838271658           NaN                    NaN       es  CC_BY_4_0
1  1838271657           NaN                    NaN       es  CC_BY_4_0
2  1838271656           NaN                    NaN       es  CC_BY_4_0
3  1838271655           NaN                    NaN       es  CC_BY_4_0
4  1838271654           NaN                    NaN       es  CC_BY_4_0

           modified  publisher  references  rightsHolder  type  ...  \
0  24/09/2018 12:29        NaN         NaN           NaN   NaN  ...
1  24/09/2018 12:29        NaN         NaN           NaN   NaN  ...
2  24/09/2018 12:29        NaN         NaN           NaN   NaN  ...
3  24/09/2018 12:29        NaN         NaN           NaN   NaN  ...
4  24/09/2018 12:29        NaN         NaN           NaN   NaN  ...

   publishedByGbifRegion  level0Gid  level0Name level1Gid  level1Name  \
0                 EUROPE        ESP       Spain   ESP.1_1   Andalucía
1                 EUROPE        ESP       Spain   ESP.1_1   Andalucía
2                 EUROPE        ESP       Spain   ESP.1_1   Andalucía
3                 EUROPE        ESP       Spain   ESP.1_1   Andalucía
4                 EUROPE        ESP       Spain   ESP.1_1   Andalucía

   level2Gid  level2Name    level3Gid  level3Name  iucnRedListCategory
0  ESP.1.8_1     Sevilla  ESP.1.8.3_1  n.a. (228)                   NE
1  ESP.1.8_1     Sevilla  ESP.1.8.3_1  n.a. (228)                   NE
2  ESP.1.8_1     Sevilla  ESP.1.8.5_1  n.a. (230)                   NE
3  ESP.1.8_1     Sevilla  ESP.1.8.5_1  n.a. (230)                   NE
4  ESP.1.8_1     Sevilla  ESP.1.8.3_1  n.a. (228)                   NE

[5 rows x 223 columns]

C:\Users\Administrator\AppData\Local\Temp\ipykernel_7884\1910875147.py:4: DtypeWarning: Columns (72) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

In [16]:
# Información general sobre el DataFrame
print(df.info())

# Estadísticas descriptivas para datos numéricos
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81908 entries, 0 to 81907
Columns: 223 entries, gbifID to iucnRedListCategory
dtypes: float64(150), int64(17), object(56)
memory usage: 139.4+ MB
None
             gbifID  accessRights  bibliographicCitation  publisher  \
count  8.190800e+04           0.0                    0.0        0.0
mean   1.838231e+09           NaN                    NaN        NaN
std    2.364495e+04           NaN                    NaN        NaN
min    1.838190e+09           NaN                    NaN        NaN
25%    1.838210e+09           NaN                    NaN        NaN
50%    1.838231e+09           NaN                    NaN        NaN
75%    1.838251e+09           NaN                    NaN        NaN
max    1.838272e+09           NaN                    NaN        NaN

       references  rightsHolder  type  institutionID  collectionID  datasetID  \
count         0.0           0.0   0.0            0.0           0.0        0.0
mean          NaN           NaN   NaN            NaN           NaN        NaN
std           NaN           NaN   NaN            NaN           NaN        NaN
min           NaN           NaN   NaN            NaN           NaN        NaN
25%           NaN           NaN   NaN            NaN           NaN        NaN
50%           NaN           NaN   NaN            NaN           NaN        NaN
75%           NaN           NaN   NaN            NaN           NaN        NaN
max           NaN           NaN   NaN            NaN           NaN        NaN

       ...  kingdomKey  phylumKey  classKey  orderKey  familyKey   genusKey  \
count  ...     81908.0    81908.0   81908.0   81908.0    81908.0    81908.0
mean   ...         1.0       54.0     216.0     797.0     7016.0  1824090.0
std    ...         0.0        0.0       0.0       0.0        0.0        0.0
min    ...         1.0       54.0     216.0     797.0     7016.0  1824090.0
25%    ...         1.0       54.0     216.0     797.0     7016.0  1824090.0
50%    ...         1.0       54.0     216.0     797.0     7016.0  1824090.0
75%    ...         1.0       54.0     216.0     797.0     7016.0  1824090.0
max    ...         1.0       54.0     216.0     797.0     7016.0  1824090.0

       subgenusKey  speciesKey  typifiedName  relativeOrganismQuantity
count          0.0     81908.0           0.0                       0.0
mean           NaN   1824131.0           NaN                       NaN
std            NaN         0.0           NaN                       NaN
min            NaN   1824131.0           NaN                       NaN
25%            NaN   1824131.0           NaN                       NaN
50%            NaN   1824131.0           NaN                       NaN
75%            NaN   1824131.0           NaN                       NaN
max            NaN   1824131.0           NaN                       NaN

[8 rows x 167 columns]

In [17]:
#Información del nombre de las columnas
print(df.columns)

Index(['gbifID', 'accessRights', 'bibliographicCitation', 'language',
       'license', 'modified', 'publisher', 'references', 'rightsHolder',
       'type',
       ...
       'publishedByGbifRegion', 'level0Gid', 'level0Name', 'level1Gid',
       'level1Name', 'level2Gid', 'level2Name', 'level3Gid', 'level3Name',
       'iucnRedListCategory'],
      dtype='object', length=223)

In [18]:
# Contar valores nulos por columna
print(df.isnull().sum())

# Porcentaje de valores nulos por columna
missing_percentage = df.isnull().sum() / len(df) * 100
print(missing_percentage)

gbifID                       0
accessRights             81908
bibliographicCitation    81908
language                     0
license                      0
                         ...
level2Gid                    0
level2Name                   0
level3Gid                    0
level3Name                   0
iucnRedListCategory          0
Length: 223, dtype: int64
gbifID                     0.0
accessRights             100.0
bibliographicCitation    100.0
language                   0.0
license                    0.0
                         ...
level2Gid                  0.0
level2Name                 0.0
level3Gid                  0.0
level3Name                 0.0
iucnRedListCategory        0.0
Length: 223, dtype: float64

In [19]:
# Eliminar columnas con más del 30% de valores nulos
threshold = 30
columns_to_drop = missing_percentage[missing_percentage > threshold].index
df = df.drop(columns=columns_to_drop)

# Eliminar filas con valores nulos
#df = df.dropna()

# Imputar valores nulos (ejemplo: usar la media)
#df.fillna(df.mean(), inplace=True)

In [20]:
print(df.columns)

Index(['gbifID', 'language', 'license', 'modified', 'institutionCode',
       'basisOfRecord', 'occurrenceID', 'catalogNumber', 'recordedBy',
       'occurrenceStatus', 'associatedTaxa', 'eventID', 'eventDate', 'year',
       'habitat', 'samplingProtocol', 'sampleSizeValue', 'sampleSizeUnit',
       'continent', 'countryCode', 'stateProvince', 'county',
       'decimalLatitude', 'decimalLongitude', 'coordinateUncertaintyInMeters',
       'footprintWKT', 'scientificName', 'kingdom', 'phylum', 'class', 'order',
       'family', 'genus', 'genericName', 'specificEpithet', 'taxonRank',
       'taxonomicStatus', 'datasetKey', 'publishingCountry', 'lastInterpreted',
       'elevation', 'elevationAccuracy', 'hasCoordinate',
       'hasGeospatialIssues', 'taxonKey', 'acceptedTaxonKey', 'kingdomKey',
       'phylumKey', 'classKey', 'orderKey', 'familyKey', 'genusKey',
       'speciesKey', 'species', 'acceptedScientificName',
       'verbatimScientificName', 'protocol', 'lastParsed', 'lastCrawled',
       'repatriated', 'projectId', 'isSequenced', 'gbifRegion',
       'publishedByGbifRegion', 'level0Gid', 'level0Name', 'level1Gid',
       'level1Name', 'level2Gid', 'level2Name', 'level3Gid', 'level3Name',
       'iucnRedListCategory'],
      dtype='object')

In [21]:
# Eliminar columnas específicas
columns_to_remove = [
       'language', 'license', 'modified','institutionCode',
       'basisOfRecord', 'occurrenceID', 'catalogNumber', 'recordedBy','associatedTaxa','eventID', 'eventDate',
       'habitat', 'samplingProtocol','continent', 'countryCode','scientificName', 'kingdom', 'phylum', 'class',
        'order','family', 'genus', 'genericName', 'specificEpithet', 'taxonRank', 'taxonomicStatus', 'datasetKey',
         'publishingCountry', 'lastInterpreted','taxonKey', 'acceptedTaxonKey', 'kingdomKey',
       'phylumKey', 'classKey', 'orderKey', 'familyKey', 'genusKey',
       'speciesKey', 'species', 'acceptedScientificName',
       'verbatimScientificName', 'protocol', 'lastParsed', 'lastCrawled',
       'repatriated', 'projectId', 'isSequenced', 'gbifRegion',
       'publishedByGbifRegion', 'level0Gid', 'level0Name', 'level1Gid',
       'level1Name', 'level2Gid', 'level2Name', 'level3Gid', 'level3Name',
       'iucnRedListCategory','hasCoordinate',
       'hasGeospatialIssues' ]
df = df.drop(columns=columns_to_remove)

In [22]:
df

,gbifID,occurrenceStatus,year,sampleSizeValue,sampleSizeUnit,stateProvince,county,decimalLatitude,decimalLongitude,coordinateUncertaintyInMeters,footprintWKT,elevation,elevationAccuracy
0,1838271658,ABSENT,2014,772396001,square meters,Se,Villanueva del Río y Minas,3766902,-566464,14760,MULTIPOLYGON(((-5.65338042110723 37.6716451919...,1850,530
1,1838271657,ABSENT,2002,772396001,square meters,Se,Villanueva del Río y Minas,3766902,-566464,14760,MULTIPOLYGON(((-5.65338042110723 37.6716451919...,1850,530
2,1838271656,PRESENT,2014,2224551913,square meters,Se,Villamanrique de la Condesa,3725938,-634365,11860,MULTIPOLYGON(((-6.33372060822364 37.2522219378...,465,155
3,1838271655,PRESENT,2000,2224551913,square meters,Se,Villamanrique de la Condesa,3725938,-634365,11860,MULTIPOLYGON(((-6.33372060822364 37.2522219378...,465,155
4,1838271654,PRESENT,1995,772396001,square meters,Se,Villanueva del Río y Minas,3766902,-566464,14760,MULTIPOLYGON(((-5.65338042110723 37.6716451919...,1850,530
...,...,...,...,...,...,...,...,...,...,...,...,...,...
81903,1838189755,ABSENT,2012,511267475,square meters,Al,María,3770824,-222502,7300,MULTIPOLYGON(((-2.22166285168146 37.7106385224...,11795,195
81904,1838189754,ABSENT,1995,511267475,square meters,Al,María,3770824,-222502,7300,MULTIPOLYGON(((-2.22166285168146 37.7106385224...,11795,195
81905,1838189753,ABSENT,1999,511267475,square meters,Al,María,3770824,-222502,7300,MULTIPOLYGON(((-2.22166285168146 37.7106385224...,11795,195
81906,1838189752,ABSENT,1994,511267475,square meters,Al,María,3770824,-222502,7300,MULTIPOLYGON(((-2.22166285168146 37.7106385224...,11795,195
81907,1838189751,ABSENT,2008,511267475,square meters,Al,María,3770824,-222502,7300,MULTIPOLYGON(((-2.22166285168146 37.7106385224...,11795,195

In [11]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# Normalización (valores entre 0 y 1)
scaler = MinMaxScaler()
df_normalized = pd.DataFrame(scaler.fit_transform(df.select_dtypes(include='number')), 
                             columns=df.select_dtypes(include='number').columns)

# Reemplazar en el DataFrame original
df[df_normalized.columns] = df_normalized